# 使用Ubuntu 23.10, mantic-20240216, mantic, rolling 版本作为基础镜像
FROM ubuntu:22.04 AS builder

# 阻止交互式提示
ARG DEBIAN_FRONTEND=noninteractive

# 设置工作目录
WORKDIR /env

# 更新系统并一次性安装所有必要的构建工具和库，然后清理缓存
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    curl \
    g++ \
    gcc \
    gdb \
    git \
    libicu-dev \
    libkrb5-dev \
    libssl-dev \
    libunwind8 \
    net-tools \
    openssl \
    unzip \
    zip \
    && rm -rf /var/lib/apt/lists/* \
    # 下载并构建Boost
    && curl -L https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.bz2 -o boost_1_84_0.tar.bz2 \
    && tar xjf boost_1_84_0.tar.bz2 \
    && rm boost_1_84_0.tar.bz2 \
    && mv boost_1_84_0 boost \
    && cd boost \
    && ./bootstrap.sh \
    && ./b2 cxxflags=-fPIC \
    && cd .. \
    # 下载并构建jemalloc
    && curl -L https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2 -o jemalloc-5.3.0.tar.bz2 \
    && tar xjf jemalloc-5.3.0.tar.bz2 \
    && rm jemalloc-5.3.0.tar.bz2 \
    && mv jemalloc-5.3.0 jemalloc \
    && cd jemalloc \
    && ./autogen.sh --with-jemalloc-prefix=je_ \
    && make -j$(nproc) \
    && cd .. \
    # 下载并构建OpenSSL
    && curl -L https://www.openssl.org/source/openssl-3.0.13.tar.gz -o openssl-3.0.13.tar.gz \
    && tar zxvf openssl-3.0.13.tar.gz \
    && rm openssl-3.0.13.tar.gz \
    && mv openssl-3.0.13 openssl \
    && cd openssl \
    && ./Configure \
    && make -j$(nproc) \
    && cd ..
